site_name: Godash
repo_name: 'duckpunch/godash'
repo_url: 'https://github.com/duckpunch/godash'
theme:
  name: material
  icon:
    logo: fontawesome/solid/adjust
extra_css:
  - style.css
markdown_extensions:
  - codehilite
